### ISSUE TITLE
Open safariViewController in modal

### ISSUE THREAD

**Issue by westerncj** [Belicosus/AppAuth-Ionic#11]
Is there a way to open the safariViewController inside of a modal, similar to the LinkedIn or Instagram apps, so it doesn't look like you've left the application? Also, can you hide some of the bottom buttons?

**Comment by wi3land** [comment]
There isn't no, I did look into this as i used to use the inAppBrowser which is no longer supported for oauth but is used as a backup if safari or chrome tabs is unavailable.

In inAppBrowser you can hide the location bar from the app and make the webpage full screen. But this isn't supported by the safari view controller cordova plugin.

**Comment by westerncj** [comment]
I'm looking for a effect similar to the Instagram app where I can still show the logo of the application and it looks like it's more apart of the app itself. Is there any other way to achieve this?

**Comment by wi3land** [comment]
i dont believe so, but if you find a solution please let me know. Before you go searching though, Embedded IFrames are not supported and neither is inAppBrowser.

**Comment by westerncj** [comment]
Ok thanks for your help. Do you know if InAppBrowser is supported for Identity Server?

**Comment by wi3land** [comment]
Sorry I am probably not being clear here. When I say they are not supported. I mean that it is not recommended for use with Oauth 2 login flows. This will be because of some sort of security risk associated with using these features. There is nothing stopping you from using an InAppBrowser, in fact the code to do so is included in this project if you remove the safari browser. It's just been deemed not 100% secure and at your own risk.

`            let options: InAppBrowserOptions = {
                location: 'no',
                zoom: 'no',
                clearcache: 'yes',
                clearsessioncache: 'yes'
            }

            this.inAppLogin = this.inAppBrowser.create(url, '_self', options);

            await this.inAppLogin.show();`

**Comment by westerncj** [comment]
Ok thanks for your help @MatrixMatt249

**Comment by chougaard** [comment]
As @MatrixMatt249 correctly states, you can't remove/hide the location bar from the ChromeTabs/SafariViewControllers.

You best option is to style the sigin page on the IdentityServer (which I believe you are using) to look more in line with your app design :)
