### ISSUE TITLE
Debugging in the browser

### ISSUE THREAD

**Issue by westerncj** [Belicosus/AppAuth-Ionic#12]
How are you currently debugging this through the browser? I've been using `ionic cordova run browser -lr`, but it just shows my url with `?code=` after clicking the login button.

**Comment by chougaard** [comment]
Can't debug in the browser, since we are using ChromeTabs/SafariViewController. There are dependent on Cordova, which is only available on the devices.

We might be able to introduce a fallback to using `window` and creating a new window/tab, but we would have to figure out how to handle the callback URL (since this shouldn't be a Custom Url Scheme then).

**Comment by MatrixMatt249** [comment]
i believe inappbrowser has a fallback for window but you will need to configure an event listener instead of using custom url scheme.

**Comment by WhatsThatItsPat** [comment]
This might be relevant to [Capacitor Integration](https://github.com/Belicosus/AppAuth-Ionic/issues/9).

My dream scenario is to do 90% of my development in the browser and the last 10% on device. And all the browser development would of course be relevant to publishing for web/pwa.

It would be great to end up with a library that switches between the two flawlessly. I think this would mean using Authorization Code Flow with PKCE for native/device and Implicit Flow for browsers. Instead of having one `RedirectUri`, the library API would need to accept URIs for both scenarios; `NativeRedirect` and `BrowserRedirect` or `PkceRedirect` and `ImplicitRedirect`, and your auth server would be set up to redirect to either.

Capacitor has a Browser API that opens the appropriate view based on platform. Perhaps it could be used, or more likely it's code imitated in a complete auth lib/plugin.

**Comment by wi3land** [comment]
just to add to this are you aware of Android remote debugging for Chrome.
its not perfect but it does add an extra level of debugging which is very limited on ionics part.
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/
